# Generated by Django 4.0.3 on 2022-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planer_manager', '0002_alter_planer_description_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image/'),
        ),
    ]
